all: main.o rules.o bot.o fila.o
	gcc -g main.o rules.o bot.o fila.o

main.o: main.c
	gcc -g -c main.c

rules.o: rules.c
	gcc -g -c rules.c

bot.o: bot.c
	gcc -g -c bot.c
fila.o: fila.c
	gcc -g -c fila.c